export const CONVERSATION_SELECTED = 'CONVERSATION_SELECTED'
export const CONVERSATION_BLOCKED = 'CONVERSATION_BLOCKED'
export const CONVERSATION_ARCHIVED = 'CONVERSATION_ARCHIVED'
export const CONVERSATION_ACTIVATED = 'CONVERSATION_ACTIVATED'
export const NEW_MESSAGE = 'NEW_MESSAGE'

export const STANDARD_MESSAGE = 1
export const APPLY_MESSAGE = 2
export const OFFER_MESSAGE = 3
export const INVITE_MESSAGE = 4
export const DECLINE_MESSAGE = 6

export const ACTIVE_CONVERSATION = 1
export const ARCHIVED_CONVERSATION = 2
export const BLOCKED_CONVERSATION = 3
export const CONVERSATION_TYPES = [
	ACTIVE_CONVERSATION,
	ARCHIVED_CONVERSATION,
	BLOCKED_CONVERSATION
]

export const TEMPLATE_SELECTED = 'template selected'

export const RU = 'ru'
export const UA = 'ua'
export const EN = 'en'
